### ISSUE TITLE
Lỗi skill Tiêu Dao và mã bài ?

### ISSUE THREAD

**Issue by cjgawatama** [jxoffline/jx1linux#12]
1, Tiêu Dao gia nhập không có skill
2, Các loại mã bài không thể sử dụng

**Comment by jxoffline** [comment]
Bác có thể cho vài hình minh hoạ hoặc các bước thực hiện như thế nào để mở mấy cái "mã bài"không? Mình chưa nghe qua khái niệm "mã bài".

**Comment by cjgawatama** [comment]
Mã bài là mấy cái lệnh bài để lấy ngựa, ID 2328-> 2334, click chuột phải để lấy ngựa đúng tên, mấy mã bài này thường mở các event sẽ được, hoặc để bán trong kỳ trân các

**Comment by cjgawatama** [comment]
thêm lỗi nữa là lỗi dump khi bấm Ctrl +~ vẫn còn
